ДЗ 1
ParzivalLone/2024-2-VK-EDU-Frontend-A-Nesterenko pull request #1
Opened 2024-09-17 21:33 UTC by ParzivalLone

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

2024-09-18 11:48 UTC, RomanBarannickov submitted a review, later dismissed
approve
@martinkomitsky, @HaseProgram, @kgrechin

2024-09-18 19:02 UTC, kgrechin requested changes

2024-09-18 19:02 UTC, kgrechin commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
а если NaN передать сработает?

2024-09-18 19:08 UTC, kgrechin commented
доп совет, не обязателен к решению, можешь подлить сразу или в следующем дз, или вообще не подливать:

в nonUniqueElements я бы подумал на тем, чтобы избавиться от двойного indexOf внутри цикла, тк  time compexity у него O(n).

подумай в сторону доп переменной, для подсчета не уникальных или о способе сразу же получить все уникальные и на основе их получить корректный результат

2024-09-18 20:47 UTC, ParzivalLone commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
Нет

2024-09-18 21:03 UTC, kgrechin commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
надо бы пофиксить

2024-09-18 21:37 UTC, ParzivalLone commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
А можно добавить метод Number.isNaN вот так expect(Number.isNaN(convertBytesToHuman(NaN))).toBe(true);

2024-09-19 15:07 UTC, RomanBarannickov commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
нужно добавить проверку на NaN внутри кода)

Ты уже по факту все написал в своем сообщение

2024-09-19 15:08 UTC, ParzivalLone commented on my-project/convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false);
Спасибо, понял)

2024-09-21 16:52 UTC, martinkomitsky approved these changes
12!

2024-09-21 16:55 UTC, merged